### ISSUE TITLE
关于Message组件的bug

### ISSUE THREAD

**Issue by Shenfq** [XNAL/don-blog-backManage#1]
`src/components/Message/index.js`，currentMsg 是一个vue实例，最后销毁的时候只是调用了`this.$destroy();`，并没有让`currentMsg  = null`。
```
showMessage (options) {
      if (!currentMsg) {
        initInstance();
      }
};
```
在第二次调用$message时，并不会重新进行实例化，创建一个新的Message添加到body中，因为这里只是销毁了vue的实例，currentMsg  这个对象任然存在。

**Comment by XNAL** [comment]
最开始写的时候是存在这个问题的，昨天已经修复了这个bug。在后面增加了promise的处理，可以看下最新的代码。

    return currentMsg.showMsgBox()
        .then(val => {
          currentMsg = null;
          return Promise.resolve(val);
        })
        .catch(err => {
          currentMsg = null;
          return Promise.reject(err);
        });
