### ISSUE TITLE
这个都有些什么功能啊?

### ISSUE THREAD

**Issue by muzishuiji** [XNAL/don-blog-backManage#2]
想知道这个博客的后台管理系统都有些什么功能?

**Comment by XNAL** [comment]
额，不好意思。这几天没查看邮件，没注意到消息。
后台管理的功能有：
1、添加和管理文章分类（已完成）；
2、添加和管理标签（已完成）；
3、添加/编辑和管理文章（markdown编辑实时保存草稿功能正在开发中）；
4、添加和管理实验室项目列表（已完成）；
5、统计图表（如不同文章访问量等统计信息，计划开发中）。
